FROM ubuntu:14.04

RUN apt-get update && apt-get install -y  curl wget build-essential
RUN wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz
RUN tar -zxf pcre-8.41.tar.gz
RUN cd pcre-8.41 \
&& ./configure \
&& make \
&& make install
RUN rm pcre-8.41.tar.gz

RUN wget http://zlib.net/zlib-1.2.11.tar.gz
RUN tar -zxf zlib-1.2.11.tar.gz
RUN cd zlib-1.2.11 \
&& ./configure \
&& make \
&& make install
RUN rm zlib-1.2.11.tar.gz

RUN wget http://www.openssl.org/source/openssl-1.0.2k.tar.gz
RUN tar -zxf openssl-1.0.2k.tar.gz
RUN cd openssl-1.0.2k \
&& ./config \
--prefix=/usr \
&& make \
&& make install
RUN rm openssl-1.0.2k.tar.gz

RUN wget http://nginx.org/download/nginx-1.2.0.tar.gz
RUN tar zxf nginx-1.2.0.tar.gz
RUN cd nginx-1.2.0 \
&& ./configure \
--sbin-path=/usr/local/nginx/nginx \
--conf-path=/usr/local/nginx/nginx.conf \
--pid-path=/usr/local/nginx/nginx.pid \
--with-pcre=../pcre-8.41 \
--with-zlib=../zlib-1.2.11 \
--with-http_ssl_module \
--with-openssl=../openssl-1.0.2k \
--with-http_gzip_static_module \
--with-http_stub_status_module \
&& make \
&& make install
RUN rm nginx-1.2.0.tar.gz
ADD nginx/nginx /etc/init.d/
RUN adduser --system --no-create-home --disabled-login --disabled-password --group nginx
RUN chmod +x /etc/init.d/nginx
RUN /usr/sbin/update-rc.d -f nginx defaults
EXPOSE 8080

# PHP
RUN apt-get install -y software-properties-common
RUN apt-get install -y language-pack-en-base
RUN DEBIAN_FRONTEND=noninteractive LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php && apt-get update
RUN apt-get install -y php5.6-fpm
RUN apt-get install -y php5-mysql php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl snmp
RUN apt-get install -y php-raphf php-propro php5-redis php5-intl php5.6-mbstring php5.6-dom php5.6-mysqli php-memcached php5.6-http php5.6-imagick php5.6-redis
ENTRYPOINT service nginx start && /bin/bash